### PR TITLE
Update to use new menu entry creation and fixed item overlay

### LINKED ISSUE #6: Plugin disappeared?
I loved using this plugin. Where did it go? :(

### PR DESCRIPTION
**Pull request by adamk33n3r**
I also did a little cleanup (but not too much style wise) and added a new option to let the overlay position not reset on show.

Fixes #6

### CODE REVIEW

**Comment by dseeler** [comment]
Code looks good, will fully inspect and test tmrw

File: src/main/java/com/bankxpvalue/BankXpValueConfig.java [hunk 1]
```diff
@@ -24,17 +24,27 @@ default boolean showTutorial(){
     void setTutorial(boolean tutorial);
 
     @ConfigItem(
-            position = 2,
+        position = 2,
+        keyName = "createInCenter",
+        name = "Create overlay in center",
+        description = "Creates the overlay in the center of the bank window"
```
Comment (dseeler) [inline src/main/java/com/bankxpvalue/BankXpValueConfig.java:30]: I don't understand what this is supposed to do exactly. You said it `lets the overlay position not reset on show`, but that has nothing to do with this config description... Despite that, I don't see the difference between this and the config setting I had for locking the overlay in the center.

Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValueConfig.java:30]: For sure. So it "lets the overlay position not reset on show" when you set it to false. I am defaulting it to `true` on line 33 just so that current behavior is maintained. It's similar to the `keepFixed` config, but this is just controlling whether it is set to the center `onShow`. In this case, if you have `keepFixed == true` then this setting does nothing. But with `keepFixed == createInCenter == false` then when I toggle the overlay, it remains where I left it.

If you can think of a more concise configuration, let me know. I just wanted to not touch existing code as much as possible.

Comment (dseeler) [reply src/main/java/com/bankxpvalue/BankXpValueConfig.java:30]: Ohhh I see I see. I like that. Instead of making a new menu entry, I think having it be the default behavior when `keepFixed == false` would be optimal. What do you think?

Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValueConfig.java:30]: I think that makes sense. Having it appear in the center every time it is opened (when not keeping it fixed) isn't that useful or helpful in my opinion. I'll make the change!

File: src/main/java/com/bankxpvalue/BankXpValuePlugin.java [hunk 2]
```diff
@@ -82,69 +79,45 @@ public void onMenuEntryAdded(MenuEntryAdded event){
...
-        bankedXp.setOption("Toggle Banked XP");
-        bankedXp.setTarget("");
-        bankedXp.setType(MenuAction.WIDGET_FOURTH_OPTION.getId() + 2000);
-        bankedXp.setIdentifier(event.getIdentifier());
-        bankedXp.setParam0(event.getActionParam0());
-        bankedXp.setParam1(event.getActionParam1());
-        entries[entries.length - 1] = bankedXp;
-
-        client.setMenuEntries(entries);
+            client.createMenuEntry(-1)
```
Comment (dseeler) [inline src/main/java/com/bankxpvalue/BankXpValuePlugin.java:83]: Code looks great, but the only thing is is that if you enable the tutorial while you have the overlay position saved outside of the center, the tutorial overlay looks bugged (its position is fixed too).

I'm not sure why anyone would enable the tutorial after already using the plugin, but just to keep everything bug-free, perhaps we should toggle the `keepFixed` option when the user enables the tutorial. We don't even have to keep it enabled, just turning it on and off would reset the position of the overlay to the center and match the tutorial text. What do you think?

File: src/main/java/com/bankxpvalue/BankXpValuePlugin.java [hunk 3]
```diff
@@ -82,69 +79,45 @@ public void onMenuEntryAdded(MenuEntryAdded event){
             return;
         }
 
-        MenuEntry[] entries = client.getMenuEntries();
-
         if (config.showTutorial()){
```
Comment (dseeler) [inline src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: Code looks great, but the only thing is is that if you enable the tutorial while you have the overlay position saved outside of the center, the tutorial overlay looks bugged (its position is fixed too).

I'm not sure why anyone would enable the tutorial after already using the plugin, but just to keep everything bug-free, perhaps we should toggle the `keepFixed` option when the user enables the tutorial. We don't even have to keep it enabled, just turning it on and off would reset the position of the overlay to the center and match the tutorial text. What do you think?

Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: Hmmm....I'll look into it, but I'm wondering if it would just be better to move the tutorial overlay.

Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: Another option is just to not let the users turn on the tutorial again by hiding that config setting :P

Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: Though I guess that doesnt solve the issue completely because on first run it won't be centered...will it? I didn't try that case. What happens on first run? Maybe we should default `keepFixed` to `true`

Comment (dseeler) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: I tried the dynamic tutorial overlay implementation when I first wrote the plugin, and I couldn't figure it out. I think that was part of the reason why I kept the banked xp overlay fixed in the center. I mean, if you want to try to figure it out yourself, be my guest lol. If not, I honestly think that just hiding the tutorial config setting after first use is the best way to go. I'll accept that route.

File: src/main/java/com/bankxpvalue/BankXpValueConfig.java (hunk 1 above)
Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValueConfig.java]: Hey I was just thinking....is keepFixed really even desired? Like, I see trying to drag the overlay away and it snapping back as an annoyance. It seems like the only options we'd really need are "appear in last location" and "appear in center". Doing it that way would simplify the code some I think, and allow the user to be able to drag the overlay outside of the bank temporarily. Thoughts?

File: src/main/java/com/bankxpvalue/BankXpValuePlugin.java (hunk 3 above)
Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: Cool, I'll give it a shot tonight when I have some time!

File: src/main/java/com/bankxpvalue/BankXpValueConfig.java (hunk 1 above)
Comment (dseeler) [reply src/main/java/com/bankxpvalue/BankXpValueConfig.java]: Hmmm, I see what you're saying. I think having it in the center should always be the default position (assuming the user does _not_ want to move it), otherwise, it would appear awkwardly on the screen somewhere. If you can have it so that the center is the default position, I'm all for making those changes!

File: src/main/java/com/bankxpvalue/BankXpValuePlugin.java [hunk 4]
```diff
@@ -166,7 +139,7 @@ public void onConfigChanged(ConfigChanged configChanged){
             overlayManager.remove(itemOverlay);
```
Comment (adamk33n3r) [inline src/main/java/com/bankxpvalue/BankXpValuePlugin.java:139]: @dseeler what is this code for? Is this for `runelite.bankxpvalueplugin` aka when you toggle the plugin on or off? Shouldn't that be handled by `startUp` and `shutDown`?

File: src/main/java/com/bankxpvalue/BankXpValuePlugin.java (hunk 3 above)
Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: I got it working, it follows the overlay around when you drag it even :)

Comment (dseeler) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: Nice!!!! I just played around with it and it looks great! 👏🏼

My only concern is that the overlay does not go back to the default center position when you reset the plugin settings -- it stays where you moved it. Can you resolve this?

https://user-images.githubusercontent.com/47870467/149635264-6e5949c4-e85a-4ab4-b4b7-64c00efd4522.mov

File: src/main/java/com/bankxpvalue/BankXpValueConfig.java [hunk 5]
```diff
@@ -26,10 +26,10 @@ default boolean showTutorial(){
     @ConfigItem(
             position = 2,
             keyName = "keepFixed",
-            name = "Lock overlay in center",
-            description = "Keeps the overlay fixed in the center"
+            name = "Reset overlay to center",
+            description = "Resets the overlay to the center of the bank window when shown"
```
Comment (dseeler) [inline src/main/java/com/bankxpvalue/BankXpValueConfig.java:30]: Do you know how if you hold Alt (or Option on mac) + right click an overlay, it resets to the default position? I'm almost thinking we should remove this config option and just implement the alt + right click event handler so that it maintains that behavior/consistency. What do you think?

File: src/main/java/com/bankxpvalue/BankXpValuePlugin.java (hunk 4 above)
Comment (dseeler) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:143]: We need to keep this. `startUp` and `shutDown` are handlers for when the plugin _is_ enabled but should/should not be running. The code above is a higher-level event handler for when the plugin itself is turned off (`shutDown` does not handle this). It is necessary to revert the plugin back to its default state.

Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:143]: In my testing `shutDown` is called when you turn the plugin off. I just put a log in `shutDown` and when i flip the toggle it prints it.

File: src/main/java/com/bankxpvalue/BankXpValueConfig.java (hunk 5 above)
Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValueConfig.java:30]: Oh that's a neat idea. Ya that behavior doesn't exist as far as I know. I'm not sure if you can get click events on your overlay though can you?

File: src/main/java/com/bankxpvalue/BankXpValuePlugin.java (hunk 3 above)
Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: Regarding this, the location that is saved is namespaced to runelite so resetting it wont effect it. And I'm not sure it's possible to hook that event. It looks like this `runelite.BankXpValueOverlay_preferredLocation=157\:69`

File: src/main/java/com/bankxpvalue/BankXpValueConfig.java (hunk 5 above)
Comment (dseeler) [reply src/main/java/com/bankxpvalue/BankXpValueConfig.java:30]: I mean you should be able to considering the right click reset already exists, but I'm not sure. The config options works fine if not.

File: src/main/java/com/bankxpvalue/BankXpValuePlugin.java (hunk 3 above)
Comment (dseeler) [reply src/main/java/com/bankxpvalue/BankXpValuePlugin.java:82]: Ah I see I see. This is fine then.

**Comment by dseeler** [comment]
Last thing, if the user has the banked xp overlay up and toggles the `resetToCenter` option, I think it should immediately reset instead of just resetting upon reopening it. Can you keep the current logic you have but just add a condition in the `onConfigChanged` handler that executes `overlay.resetToCenter()` when that option is toggled and the overlay is present?

File: src/main/java/com/bankxpvalue/BankXpValueConfig.java (hunk 5 above)
Comment (adamk33n3r) [reply src/main/java/com/bankxpvalue/BankXpValueConfig.java:30]: Sorry, what do you mean the right click reset already exists? I'm not following 😅

**Comment by adamk33n3r** [comment]
> Last thing, if the user has the banked xp overlay up and toggles the `resetToCenter` option, I think it should immediately reset instead of just resetting upon reopening it. Can you keep the current logic you have but just add a condition in the `onConfigChanged` handler that executes `overlay.resetToCenter()` when that option is toggled and the overlay is present?

Done! 😃 Is there anything else I'm forgetting? I'd love to get this update out in the main client <3

**Comment by dseeler** [comment]
> > Last thing, if the user has the banked xp overlay up and toggles the `resetToCenter` option, I think it should immediately reset instead of just resetting upon reopening it. Can you keep the current logic you have but just add a condition in the `onConfigChanged` handler that executes `overlay.resetToCenter()` when that option is toggled and the overlay is present?
> 
> Done! 😃 Is there anything else I'm forgetting? I'd love to get this update out in the main client <3

I found a bug -- toggling the `resetToCenter` option while the tutorial is active causes the overlay to disappear. Please fix this and it should be good to go for the main client :)

https://user-images.githubusercontent.com/47870467/150235766-02bce8eb-dd4f-4a25-b0db-e8d0c9e7b81f.mov

**Comment by dseeler** [comment]
> > Last thing, if the user has the banked xp overlay up and toggles the `resetToCenter` option, I think it should immediately reset instead of just resetting upon reopening it. Can you keep the current logic you have but just add a condition in the `onConfigChanged` handler that executes `overlay.resetToCenter()` when that option is toggled and the overlay is present?
> 
> Done! 😃 Is there anything else I'm forgetting? I'd love to get this update out in the main client <3

I found a bug -- toggling the resetToCenter option while the tutorial is active causes the overlay to disappear. Please fix this and it should be good to go for the main client :)

https://user-images.githubusercontent.com/47870467/150236541-145facaa-383c-4dd9-bd0d-3c34962e593b.mov

**Comment by adamk33n3r** [comment]
Fixed. It was actually a bug that happened if you toggled _any_ config option. Now we're correctly only running the code when the config item changed was show tutorial!

**Comment by adamk33n3r** [comment]
Wooo 🎉
